### ISSUE TITLE
Virus protection marks patcher as trojan

### ISSUE THREAD

**Issue by Arfentul** [NicholasMoser/Six-Patches-Of-Pain#1]
![image](https://user-images.githubusercontent.com/65301897/113009285-ce9b7e80-9145-11eb-9215-92bb7fe1e120.png)

Hi Kitesage! This is Clemente from the Discord. My computer also marked the patcher as a trojan so I thought this screenshot might be helpful.

McAfee even straight up permanently deleted the .exe -_-
This screenshot is from Windows Defender.

**Comment by Arfentul** [comment]
Update: Windows defender also deletes it

**Comment by NicholasMoser** [comment]
Ugh. I had it working fine with Windows Defender originally.

It doesn't like the executable because it downloads a file from the internet and executes it (that file being the patch). I'll look into what it takes to get around this sometime in the next few days.

**Comment by NicholasMoser** [comment]
This has been fixed in version 1.0.1
https://github.com/NicholasMoser/Six-Patches-Of-Pain/releases/tag/1.0.1
