### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by RetroGameTalk** [NicholasMoser/Six-Patches-Of-Pain#13]
I want to understand what this does but i don't see any info on the repo description.
Seems like 6 patches for the game but what they do? Any info is appreciated.

**Comment by NicholasMoser** [comment]
This is an automatic patcher for a community mod for Naruto GNT4 on the GameCube. You can find more info and a discord for the mod here: https://gnt4.online/

**Comment by NicholasMoser** [comment]
It's called Six Patches of Pain as a play-on words of https://naruto.fandom.com/wiki/Six_Paths_of_Pain

**Comment by RetroGameTalk** [comment]
Wooooaaah haha thanks!
