### ISSUE TITLE
Unable to patch 1.7.2 on MacOS Sonoma (Apple Silicon)

### ISSUE THREAD

**Issue by TheExcitedTech** [NicholasMoser/Six-Patches-Of-Pain#14]
I was able to patch 1.7.1 in Janurary 2024 without an issue. However, when I try to patch 1.7.2 on macOS. I receive this error. I verified that I don't have any CLI patchers installed or in my $PATH (just in case it was using the wrong binary)

I verified that the binary was bootable (while in terminal in dir; chmod +x Six-Patches-Of-Pain)
I deleted and downloaded a fresh copy of Six-Patches-Of-Pain just in case (I already had 2.0.0 but I figured let me try)

I can successfully patch 1.7.2 on my Windows VM.

I get the same error when I run ./Six-Patches-Of-Pain -specific or ./Six-Patches-Of-Pain.

````
Enter the number of the wished release: 0
Downloading: 1.7.2
111.37 MB / 111.37 MB [------------------------------] 100.00% 37.94 MB p/s 3.1s

Patching GNT4...
671.09 MB / 1.46 GB [----------------->____________________] 45.97% 12.64 MB p/spanic: open data/patch.xdelta: too many open files

goroutine 1 [running]:
main.check(...)
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:797
main.patchWithXdelta(0x1420318, 0xc00009e038, 0xc0000a4ae0, 0xf, 0x13b3d15, 0x11, 0x1)
	D:/Code/Six-Patches-Of-Pain/xdelta.go:111 +0x1168
main.patchGNT4(0xc0001200c0, 0x2b, 0x0, 0x0, 0x0, 0x1, 0xc0000a4ae0, 0xf)
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:440 +0x419
main.main()
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:101 +0x1e5
````

````
Starting Six Patches of Pain 2.0.0....

Validating GNT4 ISO is not modified...
1.46 GB / 1.46 GB [---------------------------------] 100.00% 35.73 GB p/s 200ms

There is a new version of SCON4 available: 1.7.2
Downloading: 1.7.2
111.37 MB / 111.37 MB [------------------------------] 100.00% 30.83 MB p/s 3.8s

Patching GNT4...
671.09 MB / 1.46 GB [----------------->____________________] 45.97% 13.56 MB p/spanic: open data/patch.xdelta: too many open files

goroutine 1 [running]:
main.check(...)
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:797
main.patchWithXdelta(0x1420318, 0xc000092058, 0xc000285110, 0xf, 0x13b3d15, 0x11, 0x1)
	D:/Code/Six-Patches-Of-Pain/xdelta.go:111 +0x1168
main.patchGNT4(0xc000020120, 0x2b, 0x0, 0x0, 0x0, 0x1, 0xc000285110, 0xf)
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:440 +0x419
main.main()
	D:/Code/Six-Patches-Of-Pain/six_patches_of_pain.go:101 +0x1e5
````

**EDIT**: I noticed I have Go installed, I wonder if that is causing it now that I look at the log. I have go version go1.21.6 darwin/arm64 installed

**EDIT UPDATE:** I uninstalled Go from my OS to see if issue was due to difference in Go versions from the binary and my environment without Go issue perists. Power cycling the machine didn't resolve the issue either.

**Comment by TheExcitedTech** [comment]
I compiled the binary on my system (macOS Sonoma 14.3.1 on MacBook Pro M1 Max) with Go and that resolved the issue. 

Marking as closed.

**Comment by NicholasMoser** [comment]
Interesting. The `too many open files` in the error seems odd, but glad to hear you have it resolved.
