### ISSUE TITLE
.nkit.iso ROM

### ISSUE THREAD

**Issue by Arfentul** [NicholasMoser/Six-Patches-Of-Pain#5]
The patcher does not behave as expected with a .nkit.iso ROM.
The patcher asks to modify the iso before patching, and then runs to completion, but does not produce an SCON4.iso file.

![nkit](https://user-images.githubusercontent.com/65301897/173070201-de9b6f20-2fc1-41b0-9d80-8019fe044503.png)

**Comment by Arfentul** [comment]
Seems like there should be a check to see if it's an nkit.iso file, and if so, ask the user to convert to .iso first, unless it's somehow possible to also do that conversion with the patcher.

**Comment by NicholasMoser** [comment]
Based on information from [this Dolphin progress report](https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/#about-the-nkit-format) and this [file format page](https://docs.fileformat.com/disc-and-media/nkit/), Nkit files do appear to be lossless, so the patcher should be able to be restore it to an ISO file. The Dolphin progress report states that Nkit has a lot of features that may be difficult to reimplement, but I'll see what I can do.

At the very least I can go with your first option of just telling the user to go do it.
